### PR TITLE
added ability to save multiple workflows locally, and ability to export

### PR DESCRIPTION
**Pull request by Festivejelly**
I've added functionality to allow you save multiple workflows to local storage and in turn load them.

I've also added the ability to export to JSON and import to json for when you want to share across devices.

This is just a draft so any feedback is welcome but I thought id share it as it has been useful to me.

To show the new options you first click More...

image

Then you will see different options

image

- You can hide the extra options by clicking Less...
- When you enter a save name and click save, it will use this as the key in local storage and it will add that entry to the drop down list.
- The drop down list is populated from the keys in local storage. It will ignore the default latheCode key.
- When clicking export it will add all of the local storage contents including the default latheCode to a JSON file which you can download.
- You can then import this json file on another machine in order to share the lathecode

image

Future ideas:

Some sort of collections for different parts might be nice here. I make valves and I have all sorts of different designs so grouping them in collections would be useful.

Also importing from a URL such as github might be useful too as it would make it trivial to share designs.

### CODE REVIEW

**Comment by kachurovskiy** [comment]
Hi Nicholas, nice work. Are you saving gcode or lathecode? It's hard to see what changed since there's a lot of reformatting going on. Would he nice to minimize the diff if possible. Also can you please make the new UI section initially hidden and only shown when a "..." button is pressed or something like that? Happy holidays!

**Comment by Festivejelly** [comment]
> Hi Nicholas, nice work. Are you saving gcode or lathecode? It's hard to see what changed since there's a lot of reformatting going on. Would he nice to minimize the diff if possible. Also can you please make the new UI section initially hidden and only shown when a "..." button is pressed or something like that? Happy holidays!

Its just saving the lathecode. Appologies for the amount of changes my VSCode formatting changes a lot of lines. I can for sure add a ... button which can expand and collapse the section.

**Comment by kachurovskiy** [comment]
Thank you! Will get back to you on the weekend once I'm back at my computer.

**Comment by Festivejelly** [comment]
You can play around with it here https://festivejelly.github.io/lathecode/

On this one ive made the gcode window visible by default for my usage (not in this PR) and added the save mechanism to that too.
The main reason for this is that ill probably be hand coding some of the gcode (for boring operations etc).

**Pull request merged**
